export const KNOWN_BRANDS = [
  'philco', 'mondial', 'oster', 'arno', 'electrolux', 'walita', 'britania',
  'samsung', 'apple', 'xiaomi', 'motorola', 'lg', 'jbl', 'lenovo', 'dell',
  'asus', 'acer', 'nike', 'adidas', 'caloi', 'taiff', 'playstation', 'xbox',
] as const

export const PRODUCT_TYPES = {
  air_fryer: /\bair\s*fryer\b/i,
  running_shoe: /\b(tenis|tênis).*(corrida|running)|(corrida|running).*\b(tenis|tênis)\b/i,
  coffee_maker: /\b(cafeteira|coffee\s*maker)\b/i,
  stand_mixer: /\b(batedeira|planetaria|planetária)\b/i,
  blender: /\bliquidificador\b/i,
  hand_blender: /\bmixer\b/i,
  sandwich_maker: /\b(sanduicheira|sanduicheira)\b/i,
  electric_kettle: /\b(chaleira\s*eletrica|chaleira\s*elétrica)\b/i,
  electric_pan: /\b(panela\s*eletrica|panela\s*elétrica)\b/i,
  food_processor: /\b(processador\s*(de\s*)?alimentos?|mini\s*processador)\b/i,
  electric_oven: /\b(forno\s*eletrico|forno\s*elétrico)\b/i,
  popcorn_maker: /\bpipoqueira\s*eletrica|pipoqueira\s*elétrica\b/i,
  egg_cooker: /\bcozedor\s*de\s*ovos?\b/i,
  juicer: /\b(espremedor|extrator)\s*eletrico|espremedor\s*elétrico\b/i,
  vacuum_cleaner: /\b(aspirador|robo\s*aspirador|robô\s*aspirador)\b/i,
  washing_machine: /\b(m[aá]quina\s*de\s*lavar|lavadora)\b/i,
  refrigerator: /\b(geladeira|refrigerador)\b/i,
  smartphone: /\b(celular|smartphone)\b/i,
  tablet: /\btablet\b/i,
  notebook: /\b(notebook|laptop)\b/i,
  monitor: /\bmonitor\b/i,
  television: /\b(smart\s*tv|televis[aã]o|televisor)\b/i,
  headphones: /\b(fone|fones|headphone|headset|earbuds?)\b/i,
  smartwatch: /\b(smart\s*watch|relogio\s*inteligente|relógio\s*inteligente)\b/i,
  printer: /\b(impressora|multifuncional)\b/i,
  game_console: /\b(playstation|ps[45]|xbox|nintendo\s*switch)\b/i,
  camera: /\b(camera|câmera|gopro)\b/i,
  dress: /\b(vestido)\b/i,
  t_shirt: /\b(camiseta|camisa)\b/i,
  pants: /\b(calca|calça|jeans|bermuda|shorts)\b/i,
  jacket: /\b(jaqueta|casaco|blusa|moletom)\b/i,
  casual_shoe: /\b(tenis|tênis)\b/i,
  sandal: /\b(sandalia|sandália|chinelo)\b/i,
  boot: /\b(bota|coturno)\b/i,
  hair_dryer: /\b(secador\s*(de\s*)?cabelo)\b/i,
  hair_straightener: /\b(chapinha|prancha\s*(de\s*)?cabelo)\b/i,
  skincare: /\b(hidratante|protetor\s*solar|serum|sérum|skincare)\b/i,
  makeup: /\b(base|batom|mascara|máscara|corretivo|maquiagem)\b/i,
  bicycle: /\bbicicleta\b/i,
  fitness: /\b(halter|esteira|academia|fitness|yoga|colchonete)\b/i,
} as const

export const ACCESSORY_TERMS = /\b(cesto|silicone|suporte|cadarco|cadarço|refil|peca|peça|case|capa|pelicula|película|protetor|acessorio|acessório)\b/i
export const BUNDLE_TERMS = /\b(combo|kit|conjunto)\b/i
export const COUPON_TERMS = /\b(cupom|voucher|cashback)\b/i
