import marketplaceCatalog from '../../../scripts/marketplace-classification-catalog.json'

export const MERCADO_LIVRE_PRODUCT_TYPES = marketplaceCatalog.rules.map(({ type, pattern }) => ({
  type,
  pattern: new RegExp(pattern, 'i'),
}))

export const MERCADO_LIVRE_DOMAIN_TYPES = marketplaceCatalog.domains as Record<string, string>
export const MERCADO_LIVRE_CATEGORY_TYPES = marketplaceCatalog.categories as Record<string, string>

export const KNOWN_BRANDS = [
  'philco', 'mondial', 'oster', 'arno', 'electrolux', 'walita', 'britania',
  'samsung', 'apple', 'xiaomi', 'motorola', 'lg', 'jbl', 'lenovo', 'dell',
  'brastemp', 'consul', 'panasonic', 'midea', 'esmaltec', 'emma',
  'asus', 'acer', 'nike', 'adidas', 'caloi', 'taiff', 'playstation', 'xbox',
] as const

export const PRODUCT_TYPES = {
  air_fryer: /\bair\s*fryer\b/i,
  running_shoe: /\b(tenis|tênis).*(corrida|running)|(corrida|running).*\b(tenis|tênis)\b/i,
  coffee_maker: /\b(cafeteira|coffee\s*maker)\b/i,
  stand_mixer: /\b(batedeira|planetaria|planetária)\b/i,
  blender: /\bliquidificador\b/i,
  hand_blender: /\bmixer\b/i,
  sandwich_maker: /\b(sanduicheira|sanduicheira)\b/i,
  electric_kettle: /\b(chaleira\s*eletrica|chaleira\s*elétrica)\b/i,
  electric_pan: /\b(panela\s*eletrica|panela\s*elétrica)\b/i,
  food_processor: /\b(processador\s*(de\s*)?alimentos?|mini\s*processador)\b/i,
  electric_oven: /\b(forno\s*eletrico|forno\s*elétrico)\b/i,
  popcorn_maker: /\bpipoqueira\b/i,
  egg_cooker: /\bcozedor\s*de\s*ovos?\b/i,
  juicer: /\b(espremedor|extrator)\b(?:\s+(?:de\s+)?(?:frutas?|sucos?)|\s*(?:el[eé]trico|c[ií]trico))?/i,
  vacuum_cleaner: /\b(aspirador|robo\s*aspirador|robô\s*aspirador)\b/i,
  washing_machine: /\b(m[aá]quina\s*de\s*lavar|lavadora)\b/i,
  washer_dryer: /\b(lava\s*e\s*seca|lava[-\s]*e[-\s]*seca)\b/i,
  refrigerator: /\b(geladeira|refrigerador)\b/i,
  dishwasher: /\b(lava[-\s]*lou[cç]as)\b/i,
  cooktop: /\bcook\s*top\b/i,
  microwave: /\bmicro[-\s]*ondas\b/i,
  air_conditioner: /\bar[-\s]*condicionado\b/i,
  stove: /\bfog[aã]o\b/i,
  sofa: /\bsof[aá]\b/i,
  wardrobe: /\bguarda[-\s]*roupa\b/i,
  bed: /\bcama\b/i,
  mattress: /\bcolch[aã]o\b/i,
  dining_table: /\bmesa\s+(?:de\s+)?jantar\b/i,
  desk: /\bescrivaninha\b/i,
  office_chair: /\bcadeira\s+(?:de\s+)?(?:escrit[oó]rio|gamer)\b/i,
  tv_rack: /\b(?:rack|painel)\s+(?:para\s+)?tv\b/i,
  dresser: /\bc[oô]moda\b/i,
  smart_bulb: /\b(l[aâ]mpada|luz)\s+(?:inteligente|smart)|smart\s*bulb\b/i,
  smart_plug: /\btomadas?\s+(?:inteligentes?|smart)\b/i,
  smartphone: /\b(celular|smartphone|iphone|galaxy|redmi)\b/i,
  charger: /\bcarregador(?:es)?\b/i,
  power_bank: /\bpower\s*bank\b/i,
  tablet: /\btablet\b/i,
  external_hdd: /\b(?:hd|hdd|disco|disco\s+r[ií]gido)\s*(?:externo|externa|port[aá]til)\b/i,
  notebook: /\b(notebook|laptop)\b/i,
  desktop: /\b(computador|desktop|pc\s*gamer)\b/i,
  monitor: /\bmonitor\b/i,
  keyboard: /\b(teclado(?:s)?|keyboard)\b/i,
  mouse: /\bmouse(?:s)?\b/i,
  webcam: /\bwebcam\b/i,
  ssd: /\bssd\b/i,
  router: /\b(roteador|router)\b/i,
  home_theater: /\b(home\s*theater|home\s*cinema|sistema\s+de\s+home\s*theater)\b/i,
  tv_box: /\b(?:tv|smart)\s*(?:box|stick|streaming)\b/i,
  television: /\b(smart\s*tv|televis[aã]o|televisor)\b/i,
  projector: /\bprojetor\b/i,
  headphones: /\b(fone|fones|headphone|headset|earbuds?)\b/i,
  speaker: /\b(caixa\s+de\s+som|speaker)\b/i,
  soundbar: /\bsoundbar\b/i,
  smartband: /\b(smart\s*band|mi\s*band|band\s*\d+)\b/i,
  smartwatch: /\b(smart\s*watch|relogio\s*inteligente|relógio\s*inteligente)\b/i,
  ereader: /\b(kindle|e[-\s]?reader|leitor\s+digital)\b/i,
  printer: /\b(impressora|multifuncional)\b/i,
  game_console: /\b(playstation|ps[45]|xbox|nintendo\s*switch|console(?:\s+de\s+videogame)?)\b/i,
  game_controller: /\b(controle|controlador)\s+(?:gamer|de\s+(?:jogo|videogame)|sem\s+fio|xbox)\b/i,
  drone: /\bdrone\b/i,
  camera: /\b(camera|câmera|gopro|action\s*cam)\b/i,
  smart_speaker: /\b(alexa|echo(?:\s+dot|\s+show)?)\b/i,
  cable: /\bcabo(?:s)?\b/i,
  hub: /\bhubs?\b/i,
  stand: /\bsuporte(?:s)?\b/i,
  adapter: /\badaptador(?:es)?\b/i,
  dress: /\b(vestido)\b/i,
  t_shirt: /\b(camiseta|camisa)\b/i,
  pants: /\b(calca|calça|jeans|bermuda|shorts)\b/i,

  jacket: /\b(jaqueta|casaco|blusa|moletom)\b/i,
  casual_shoe: /\b(tenis|tênis)\b/i,
  sandal: /\b(sandalia|sandália|chinelo)\b/i,
  boot: /\b(bota|coturno)\b/i,
  hair_dryer: /\b(secador\s*(de\s*)?cabelo)\b/i,
  hair_straightener: /\b(chapinha|prancha\s*(de\s*)?cabelo)\b/i,
  skincare: /\b(hidratante|protetor\s*solar|serum|sérum|skincare)\b/i,
  makeup: /\b(base|batom|mascara|máscara|corretivo|maquiagem)\b/i,
  perfume: /\b(perfume|fragrancia|fragrância|eau\s*de\s*parfum|eau\s*de\s*toilette|colonia|colônia)\b/i,
  bicycle: /\bbicicleta\b/i,
  fitness: /\b(halter|esteira|academia|fitness|yoga|colchonete|whey|suplemento|creatina)\b/i,
  automotive: /\b(pneu|calota|bateria\s*automotiva|som\s*automotivo|capacete|oleo\s*de\s*motor|óleo\s*de\s*motor|multimidia\s*automotiva)\b/i,
  tools: /\b(furadeira|parafusadeira|kit\s*ferramentas|chave\s*de\s*fenda|martelete|serra\s*eletrica|serra\s*marmore)\b/i,
  games: /\b(jogo\s*ps4|jogo\s*ps5|jogo\s*xbox|jogo\s*switch|mídia\s*física)\b/i,
} as const

export const ACCESSORY_TERMS = /\b(cesto|silicone|suporte|cadarco|cadarço|refil|peca|peça|case|capa|pelicula|película|protetor|acessorio|acessório|carregador|power\s*bank|cabo|hub|adaptador|controle)\b/i
export const BUNDLE_TERMS = /\b(combo|kit|conjunto)\b/i
export const COUPON_TERMS = /\b(cupom|voucher|cashback)\b/i
